INSERT INTO questions(content, category_id) VALUES ('﻿Из каких символов может состоять имя переменной (корректный идентификатор)?', 1);
INSERT INTO questions(content, category_id) VALUES ('Что значит слово «инициализация»?', 1);
INSERT INTO questions(content, category_id) VALUES ('На какие основные группы можно поделить типы данных?', 1);
INSERT INTO questions(content, category_id) VALUES ('Какие примитивные типы вы знаете? Назовите размерность в байтах для каждого типа.', 1);
INSERT INTO questions(content, category_id) VALUES ('Что вы знаете о преобразовании примитивных типов данных, есть ли потеря данных, можно ли преобразовать логический тип?', 1);
INSERT INTO questions(content, category_id) VALUES ('Какими значениями инициализируются переменные по умолчанию?', 1);
INSERT INTO questions(content, category_id) VALUES ('Как передается значение переменной (по ссылке/значению)?', 1);
INSERT INTO questions(content, category_id) VALUES ('Что вы знаете о функции main, какие обязательные условия ее определения?', 1);
INSERT INTO questions(content, category_id) VALUES ('Какие логические операции и операторы вы знаете?', 1);
INSERT INTO questions(content, category_id) VALUES ('В чем разница краткой и полной схемы записи логических операторов?', 1);
INSERT INTO questions(content, category_id) VALUES ('Что такое таблица истинности?', 1);
INSERT INTO questions(content, category_id) VALUES ('Что такое тернарный оператор выбора?', 1);
INSERT INTO questions(content, category_id) VALUES ('Какие унарные операции вы знаете?', 1);
INSERT INTO questions(content, category_id) VALUES ('Какая арифметическая операция выполняется при побитовом сдвиге вправо/влево?', 1);
INSERT INTO questions(content, category_id) VALUES ('Какова роль и правила написания оператора выбора (switch)?', 1);
INSERT INTO questions(content, category_id) VALUES ('Какие циклы вы знаете, в чем их отличия?', 1);
INSERT INTO questions(content, category_id) VALUES ('Что такое «итерация цикла»?', 1);
INSERT INTO questions(content, category_id) VALUES ('Какие параметры имеет цикл for, можно ли их не задать?', 1);
INSERT INTO questions(content, category_id) VALUES ('Какой оператор используется для немедленной остановки цикла?', 1);
INSERT INTO questions(content, category_id) VALUES ('Какой оператор используется для перехода к следующей итерации цикла?', 1);
INSERT INTO questions(content, category_id) VALUES ('Что такое массив?', 1);
INSERT INTO questions(content, category_id) VALUES ('Какие виды массивов вы знаете?', 1);
INSERT INTO questions(content, category_id) VALUES ('Что вы знаете о классах обертках?', 1);
INSERT INTO questions(content, category_id) VALUES ('Что такое автоупаковка (boxing/unboxing)?', 1);
INSERT INTO questions(content, category_id) VALUES ('﻿Назовите принципы ООП и расскажите о каждом.', 2);
INSERT INTO questions(content, category_id) VALUES ('Дайте определение понятию «класс».', 2);
INSERT INTO questions(content, category_id) VALUES ('Что такое поле/атрибут класса?', 2);
INSERT INTO questions(content, category_id) VALUES ('Как правильно организовать доступ к полям класса?', 2);
INSERT INTO questions(content, category_id) VALUES ('Дайте определение понятию «конструктор».', 2);
INSERT INTO questions(content, category_id) VALUES ('Чем отличаются конструкторы по-умолчанию и конструктор с параметрами?', 2);
INSERT INTO questions(content, category_id) VALUES ('Какие модификации уровня доступа вы знаете, расскажите про каждый из них.', 2);
INSERT INTO questions(content, category_id) VALUES ('Расскажите об особенностях класса с единственным закрытым (private) конструктором.', 2);
INSERT INTO questions(content, category_id) VALUES ('О чем говорят ключевые слова «this», «super», где и как их можно использовать?', 2);
INSERT INTO questions(content, category_id) VALUES ('Дайте определение понятию «метод».', 2);
INSERT INTO questions(content, category_id) VALUES ('Что такое сигнатура метода?', 2);
INSERT INTO questions(content, category_id) VALUES ('Какие методы называются перегруженными?', 2);
INSERT INTO questions(content, category_id) VALUES ('Могут ли нестатические методы перегрузить статические?', 2);
INSERT INTO questions(content, category_id) VALUES ('Расскажите о переопределение методов.', 2);
INSERT INTO questions(content, category_id) VALUES ('Может ли метод принимать разное количество параметров (аргументы переменной длины)?', 2);
INSERT INTO questions(content, category_id) VALUES ('Можно ли сузить уровень доступа/тип возвращаемого значения при переопределении метода?', 2);
INSERT INTO questions(content, category_id) VALUES ('Как получить доступ к переопределенным методам родительского класса?', 2);
INSERT INTO questions(content, category_id) VALUES ('Какие преобразования называются нисходящими и восходящими?', 2);
INSERT INTO questions(content, category_id) VALUES ('Чем отличается переопределение от перегрузки?', 2);
INSERT INTO questions(content, category_id) VALUES ('Где можно инициилизировать статические/нестатические поля?', 2);
INSERT INTO questions(content, category_id) VALUES ('Зачем нужен оператор instanceof?', 2);
INSERT INTO questions(content, category_id) VALUES ('Зачем нужны и какие бывают блоки инициализации?', 2);
INSERT INTO questions(content, category_id) VALUES ('Каков порядок вызова конструкторов и блоков инициализации двух классов: потомка и его предка?', 2);
INSERT INTO questions(content, category_id) VALUES ('Где и для чего используется модификатор abstract?', 2);
INSERT INTO questions(content, category_id) VALUES ('Можно ли объявить метод абстрактым и статическим одновременно?', 2);
INSERT INTO questions(content, category_id) VALUES ('Что означает ключевое поле static?', 2);
INSERT INTO questions(content, category_id) VALUES ('К каким конструкциям Java применим модификатор static?', 2);
INSERT INTO questions(content, category_id) VALUES ('Что будет, если в static блоке кода возникнет исключительная ситуация?', 2);
INSERT INTO questions(content, category_id) VALUES ('Можно ли перегрузить static метод?', 2);
INSERT INTO questions(content, category_id) VALUES ('Что такое вложенный статический класс, какие особенности его использования?', 2);
INSERT INTO questions(content, category_id) VALUES ('Какие особенности инициализации final static переменных?', 2);
INSERT INTO questions(content, category_id) VALUES ('Как влияет модификатор static на класс/метод/поле?', 2);
INSERT INTO questions(content, category_id) VALUES ('О чем говорит ключевое слово final?', 2);
INSERT INTO questions(content, category_id) VALUES ('Дайте определение понятию «интерфейс».', 2);
INSERT INTO questions(content, category_id) VALUES ('Какие модификаторы по умолчанию имеют поля и методы интерфейсов?', 2);
INSERT INTO questions(content, category_id) VALUES ('Почему нельзя объявить метод интерфейса с модификатором final?', 2);
INSERT INTO questions(content, category_id) VALUES ('Какие типы классов бывают в java (вложенные… и.т.д.)', 2);
INSERT INTO questions(content, category_id) VALUES ('Что вы знаете о вложенных классах, зачем они используются? Классификация, варианты использования, о нарушении инкапсуляции.', 2);
INSERT INTO questions(content, category_id) VALUES ('Каким образом из вложенного класса получить досуп к полю внешнего класса?', 2);
INSERT INTO questions(content, category_id) VALUES ('Какие особенности создания вложенных классов: простых и статических.', 2);
INSERT INTO questions(content, category_id) VALUES ('В чем разница вложенных и внутренних классов?', 2);
INSERT INTO questions(content, category_id) VALUES ('Какие классы называются анонимными?', 2);
INSERT INTO questions(content, category_id) VALUES ('Каким образом можно обратиться к локальной переменной метода из анонимного класса, объявленного в теле этого метода? Есть ли каке-нибудь ограничения для такой переменной?', 2);
INSERT INTO questions(content, category_id) VALUES ('Как связан любой пользовательский класс с классом Object?', 2);
INSERT INTO questions(content, category_id) VALUES ('Расскажите про каждый из методов класса Object.', 2);
INSERT INTO questions(content, category_id) VALUES ('Что такое метод equals(). Чем он отличается от операции ==.', 2);
INSERT INTO questions(content, category_id) VALUES ('Если вы хотите переопределить equals(), какие условия должны удовлетворяться для переопределенного метода?', 2);
INSERT INTO questions(content, category_id) VALUES ('Если equals() переопределен, есть ли какие-либо другие методы, которые следует переопределить?', 2);
INSERT INTO questions(content, category_id) VALUES ('В чем особенность работы методов hashCode и equals? Каким образом реализованы методы hashCode и equals в классе Object? Какие правила и соглашения существуют для реализации этих методов? Когда они применяются?', 2);
INSERT INTO questions(content, category_id) VALUES ('Какой метод возвращает строковое представление объекта?', 2);
INSERT INTO questions(content, category_id) VALUES ('Что будет, если переопределить equals не переопределяя hashCode? Какие могут возникнуть проблемы?', 2);
INSERT INTO questions(content, category_id) VALUES ('Есть ли какие-либо рекомендации о том, какие поля следует использовать при подсчете hashCode?', 2);
INSERT INTO questions(content, category_id) VALUES ('Как вы думаете, будут ли какие-то проблемы, если у объекта, который используется в качестве ключа в hashMap изменится поле, которое участвует в определении hashCode?', 2);
INSERT INTO questions(content, category_id) VALUES ('Чем отличается абстрактый класс о интерфейса, в каких случаях что вы будете использовать?', 2);
INSERT INTO questions(content, category_id) VALUES ('Можно ли получить доступ к private переменным классам и если да, то каким образом?', 2);
INSERT INTO questions(content, category_id) VALUES ('Модификаторы. Назначение и варианты использования.', 2);
INSERT INTO questions(content, category_id) VALUES ('Какой из модификаторов более строгий: protected или package-private?', 2);
INSERT INTO questions(content, category_id) VALUES ('Расширение модификаторов при наследовании, переопределение и сокрытие методов. Если у класса-родителя есть метод, объявленный как private, может ли наследник расширить его видимость? А если protected? А сузить видимость?', 2);
INSERT INTO questions(content, category_id) VALUES ('Модификатор abstract и final для классов/методов', 2);
INSERT INTO questions(content, category_id) VALUES ('Имеет ли смысл объявлять метод private final?', 2);
INSERT INTO questions(content, category_id) VALUES ('Какие особенности инициализации final переменных?', 2);
INSERT INTO questions(content, category_id) VALUES ('Что будет, если единственный конструктор класса объявлен как final?', 2);
INSERT INTO questions(content, category_id) VALUES ('Расширение/сужение типов в аргументах переопределяемых методов в случае, если бы в Java список формальных параметров не входил бы в сигнатуру метода.', 2);
INSERT INTO questions(content, category_id) VALUES ('Знакомы ли Вам какие-либо паттерны проектирования?', 2);
INSERT INTO questions(content, category_id) VALUES ('Расскажите про паттерн Singleton… ', 2);
INSERT INTO questions(content, category_id) VALUES ('﻿Дайте определение понятию «исключение»', 3);
INSERT INTO questions(content, category_id) VALUES ('Какова иерархия исключений.', 3);
INSERT INTO questions(content, category_id) VALUES ('Можно/нужно ли обрабатывать ошибки jvm?', 3);
INSERT INTO questions(content, category_id) VALUES ('Какие существуют способы обработки исключений?', 3);
INSERT INTO questions(content, category_id) VALUES ('О чем говорит ключевое слово throws?', 3);
INSERT INTO questions(content, category_id) VALUES ('В чем особенность блока finally? Всегда ли он исполняется?', 3);
INSERT INTO questions(content, category_id) VALUES ('Может ли не быть ни одного блока catch при отлавливании исключений?', 3);
INSERT INTO questions(content, category_id) VALUES ('Может ли один блок catch отлавливать несколько исключений (с одной и разных веток наследований)?', 3);
INSERT INTO questions(content, category_id) VALUES ('Что вы знаете об обрабатываемых и не обрабатываемых (catched/uncatched) исключениях?', 3);
INSERT INTO questions(content, category_id) VALUES ('В чем особенность RuntimeException?', 3);
INSERT INTO questions(content, category_id) VALUES ('Как написать собственное («пользовательское») исключение? Какими мотивами вы будете руководствоваться при выборе типа исключения: checked/unchecked?', 3);
INSERT INTO questions(content, category_id) VALUES ('Какой оператор позволяет принудительно выбросить исключение?', 3);
INSERT INTO questions(content, category_id) VALUES ('Есть ли дополнительные условия к методу, который потенциально может выбросить исключение?', 3);
INSERT INTO questions(content, category_id) VALUES ('Может ли метод main выбровить исключение во вне и если да, то где будет происходить обработка данного исключения?', 3);
INSERT INTO questions(content, category_id) VALUES ('Если оператор return содержится и в блоке catch и в finally, какой из них «главнее»?', 3);
INSERT INTO questions(content, category_id) VALUES ('Что такое Error? В каком случае используется Error. Приведите пример Error’а.', 3);
INSERT INTO questions(content, category_id) VALUES ('Какая конструкция используется в Java для обработки исключений?', 3);
INSERT INTO questions(content, category_id) VALUES ('Возможно ли использование блока try-finally (без catch)?', 3);
INSERT INTO questions(content, category_id) VALUES ('﻿Дайте определение понятию «коллекция».', 4);
INSERT INTO questions(content, category_id) VALUES ('Назовите преимущества использования коллекций.', 4);
INSERT INTO questions(content, category_id) VALUES ('Какие данные могут хранить коллекции?', 4);
INSERT INTO questions(content, category_id) VALUES ('Какова иерархия коллекций?', 4);
INSERT INTO questions(content, category_id) VALUES ('Что вы знаете о коллекциях типа List?', 4);
INSERT INTO questions(content, category_id) VALUES ('Что вы знаете о коллекциях типа Set?', 4);
INSERT INTO questions(content, category_id) VALUES ('Что вы знаете о коллекциях типа Map, в чем их принципиальное отличие?', 4);
INSERT INTO questions(content, category_id) VALUES ('Назовите основные реализации List, Set, Map.', 4);
INSERT INTO questions(content, category_id) VALUES ('В чем отличия/сходства List и Set?', 4);
INSERT INTO questions(content, category_id) VALUES ('Что разного/общего у классов ArrayList и LinkedList, когда лучше использовать ArrayList, а когда LinkedList?', 4);
INSERT INTO questions(content, category_id) VALUES ('В каких случаях разумно использовать массив, а не ArrayList?', 4);
INSERT INTO questions(content, category_id) VALUES ('Чем отличается ArrayList от Vector?', 4);
INSERT INTO questions(content, category_id) VALUES ('Что вы знаете о реализации классов HashSet и TreeSet?', 4);
INSERT INTO questions(content, category_id) VALUES ('Чем отличаются HashMap и TreeMap? Как они устроены и работают? Что со временем доступа к объектам, какие зависимости?', 4);
INSERT INTO questions(content, category_id) VALUES ('Что будет, если в Map положить два значения с одинаковым ключем?', 4);
INSERT INTO questions(content, category_id) VALUES ('Как задается порядок следования объектов в коллекции, как отсортировать коллекцию?', 4);
INSERT INTO questions(content, category_id) VALUES ('Дайте определение понятию «итератор».', 4);
INSERT INTO questions(content, category_id) VALUES ('Какую функциональность представляет класс Collections?', 4);
INSERT INTO questions(content, category_id) VALUES ('Почему Map не наследуется от Collection?', 4);
INSERT INTO questions(content, category_id) VALUES ('Как реализован цикл foreach?', 4);
INSERT INTO questions(content, category_id) VALUES ('Почему в классе iterator нет метода для получения следующего элемента без передвижения курсора?', 4);
INSERT INTO questions(content, category_id) VALUES ('В чем разница между Iterator и ListIterator?', 4);
INSERT INTO questions(content, category_id) VALUES ('Какие есть способы перебора всех элементов List?', 4);
INSERT INTO questions(content, category_id) VALUES ('В чем разница между интерфейсами Comparable и Comparator?', 4);
INSERT INTO questions(content, category_id) VALUES ('Какие алгоритмы сортировки Вам известны? Какие вообще знаете алгоритмы?', 4);
INSERT INTO questions(content, category_id) VALUES ('Алгоритмы. Методы сортировки', 4);
INSERT INTO questions(content, category_id) VALUES ('Как посчитать среднее массива?', 4);
INSERT INTO questions(content, category_id) VALUES ('Что быстрее, HashMap или TreeMap?', 4);
INSERT INTO questions(content, category_id) VALUES ('﻿Какие «строковые» классы вы знаете?', 5);
INSERT INTO questions(content, category_id) VALUES ('Какие основные свойства «строковых» классов (их особенности)?', 5);
INSERT INTO questions(content, category_id) VALUES ('Можно ли наследовать строковый тип, почему?', 5);
INSERT INTO questions(content, category_id) VALUES ('Дайте определение понятию конкатенация строк.', 5);
INSERT INTO questions(content, category_id) VALUES ('Как преобразовать строку в число?', 5);
INSERT INTO questions(content, category_id) VALUES ('Как сравнить значение двух строк?', 5);
INSERT INTO questions(content, category_id) VALUES ('Как перевернуть строку?', 5);
INSERT INTO questions(content, category_id) VALUES ('Как работает сравнение двух строк?', 5);
INSERT INTO questions(content, category_id) VALUES ('Как обрезать пробелы в конце строки?', 5);
INSERT INTO questions(content, category_id) VALUES ('Как заменить символ в строке?', 5);
INSERT INTO questions(content, category_id) VALUES ('Как получить часть строки?', 5);
INSERT INTO questions(content, category_id) VALUES ('Какой метод позволяет выделить подстроку в строке?', 5);
INSERT INTO questions(content, category_id) VALUES ('Какой метод вызывается для преобразования переменной в строку?', 5);
INSERT INTO questions(content, category_id) VALUES ('Как узнать значение конкретного символа строки, знаю его порядковый номер в строке?', 5);
INSERT INTO questions(content, category_id) VALUES ('Как найти необходимый символ в строке?', 5);
INSERT INTO questions(content, category_id) VALUES ('Чем отличаются и что общего у классов String, StringBuffer и StringBuilder?', 5);
